const areaList = [
  {
    name: '安徽省',
    pinyin: 'anhui',
    pinyin_title: 'A',
    value: 12,
  },
  {
    name: '澳门',
    pinyin: 'aomen',
    pinyin_title: 'A',
    value: 34,
  },
  {
    name: '北京市',
    pinyin: 'beijing',
    pinyin_title: 'B',
    value: 1,
  },
  {
    name: '重庆市',
    pinyin: 'chongqin',
    pinyin_title: 'C',
    value: 22,
  },
  {
    name: '福建省',
    pinyin: 'fujian',
    pinyin_title: 'F',
    value: 13,
  },
  {
    name: '甘肃省',
    pinyin: 'gansu',
    pinyin_title: 'G',
    value: 28,
  },
  {
    name: '广东省',
    pinyin: 'guangdong',
    pinyin_title: 'G',
    value: 19,
  },
  {
    name: '广西',
    pinyin: 'guangxi',
    pinyin_title: 'G',
    value: 20,
  },
  {
    name: '贵州省',
    pinyin: 'guizhou',
    pinyin_title: 'G',
    value: 24,
  },
  {
    name: '海南省',
    pinyin: 'hainan',
    pinyin_title: 'H',
    value: 21,
  },
  {
    name: '海外',
    pinyin: 'haiwai',
    pinyin_title: 'H',
    value: 35,
  },
  {
    name: '河北省',
    pinyin: 'hebei',
    pinyin_title: 'H',
    value: 3,
  },
  {
    name: '黑龙江',
    pinyin: 'heilongjiang',
    pinyin_title: 'H',
    value: 8,
  },
  {
    name: '河南省',
    pinyin: 'henan',
    pinyin_title: 'H',
    value: 16,
  },
  {
    name: '湖北省',
    pinyin: 'hubei',
    pinyin_title: 'H',
    value: 17,
  },
  {
    name: '湖南省',
    pinyin: 'hunan',
    pinyin_title: 'H',
    value: 18,
  },
  {
    name: '江苏省',
    pinyin: 'jiangsu',
    pinyin_title: 'J',
    value: 10,
  },
  {
    name: '江西省',
    pinyin: 'jiangxi',
    pinyin_title: 'J',
    value: 14,
  },
  {
    name: '吉林省',
    pinyin: 'jilin',
    pinyin_title: 'J',
    value: 7,
  },
  {
    name: '辽宁省',
    pinyin: 'liaoning',
    pinyin_title: 'L',
    value: 6,
  },
  {
    name: '内蒙古',
    pinyin: 'neimenggu',
    pinyin_title: 'N',
    value: 5,
  },
  {
    name: '宁夏',
    pinyin: 'ningxia',
    pinyin_title: 'N',
    value: 30,
  },
  {
    name: '青海省',
    pinyin: 'qinghai',
    pinyin_title: 'Q',
    value: 29,
  },
  {
    name: '其他',
    pinyin: 'qita',
    pinyin_title: 'Q',
    value: 36,
  },
  {
    name: '山东省',
    pinyin: 'shandong',
    pinyin_title: 'S',
    value: 15,
  },
  {
    name: '上海市',
    pinyin: 'shanghai',
    pinyin_title: 'S',
    value: 9,
  },
  {
    name: '山西省',
    pinyin: 'shanxi',
    pinyin_title: 'S',
    value: 4,
  },
  {
    name: '陕西省',
    pinyin: 'shxi',
    pinyin_title: 'S',
    value: 27,
  },
  {
    name: '四川省',
    pinyin: 'sichuan',
    pinyin_title: 'S',
    value: 23,
  },
  {
    name: '台湾',
    pinyin: 'taiwang',
    pinyin_title: 'T',
    value: 32,
  },
  {
    name: '天津市',
    pinyin: 'tianjin',
    pinyin_title: 'T',
    value: 2,
  },
  {
    name: '香港',
    pinyin: 'xianggang',
    pinyin_title: 'X',
    value: 33,
  },
  {
    name: '新疆',
    pinyin: 'xinjiang',
    pinyin_title: 'X',
    value: 31,
  },
  {
    name: '西藏',
    pinyin: 'xizang',
    pinyin_title: 'X',
    value: 26,
  },
  {
    name: '云南省',
    pinyin: 'yunnan',
    pinyin_title: 'Y',
    value: 25,
  },
  {
    name: '浙江省',
    pinyin: 'zhejiang',
    pinyin_title: 'Z',
    value: 11,
  },
]

export default areaList
